In [2]:
#Разведочный анализ данных (EDA - Exploratory Data Analysis)

from sqlalchemy import create_engine
import pandas as pd

# Инициализация подключения к хранилищу Greenplum (Используем Connection URI формулу: СУБД://Логин:Пароль@Хост:Порт/База)
engine = create_engine('postgresql://gpadmin:gpadmin@localhost:5434/dwh')

# Скачиваем репрезентативные выборки (по 1000 строк) из ядра хранилища
dwh_trips_df = pd.read_sql("SELECT * FROM dwh.taxi_trips LIMIT 100000", engine)
dwh_zones_df = pd.read_sql("SELECT * FROM dwh.taxi_zones LIMIT 100000", engine)

# Проверка качества данных и устранение аномалий
dwh_trips_df.head()
dwh_zones_df.head()
dwh_trips_df.dtypes
dwh_trips_df.isnull().sum()

# Заменяем NULL (NaN) в налоге на пробки на дефолтные нули, чтобы не сломать математику
dwh_trips_df['congestion_surcharge'] = dwh_trips_df['congestion_surcharge'].fillna(0.0)

# Фильтруем явные выбросы: оставляем только поездки с положительным чеком и дистанцией
clean_trips_df = dwh_trips_df[(dwh_trips_df['trip_distance'] >0 ) & (dwh_trips_df['total_amount'] > 0)] 
clean_trips_df.isnull().sum()

# Сборка One Big Table (Денормализация)
# Последовательно выполняем два  .merge (соединения 2ух таблиц в Pandas)
# первое соединение: Подтягиваем текстовый справочник зон к точке посадки (pulocationid), 
# переименовываем столбцы : добавляем к району, зонам слово "pickup", и чтобы не запутаться удаляем лишний технический дубликат:
obt = pd.merge(clean_trips_df, dwh_zones_df, how='left', left_on='pulocationid', right_on='locationid')
obt = obt.rename(columns={'borough': 'pickup_borough', 'zone': 'pickup_zone', 'service_zone': 'pickup_service_zone'})
obt = obt.drop(columns=['locationid'])
#Подтягиваем этот же справочник зон к точке высадки (dolocationid) и финальное переименование полей для высадки и очистка мусора.
obt_total = pd.merge(obt, dwh_zones_df, how='left', left_on='dolocationid', right_on='locationid')
obt_total = obt_total.rename(columns={'borough': 'dropoff_borough', 'zone': 'dropoff_zone', 'service_zone': 'dropoff_service_zone'})
obt_total = obt_total.drop(columns=['locationid'])

#Выводим на экран верхушку готовой широкой аналитической витрины
obt_total.head(3)

#бизнес-аналитика для дашборда
#метрика 1: количество поездок по дням;
# Подготовка временных полей: Принудительно кастим обе колонки в формат datetime
# (Это критически важно, чтобы расчет длительности поездки в минутах прошел без ошибок!)
obt_total['tpep_pickup_datetime'] = pd.to_datetime(obt_total['tpep_pickup_datetime'])
obt_total['tpep_dropoff_datetime'] = pd.to_datetime(obt_total['tpep_dropoff_datetime'])
obt_total['date_only'] = obt_total['tpep_pickup_datetime'].dt.date
obt_total['hour_only'] = obt_total['tpep_pickup_datetime'].dt.hour
trips_per_day = obt_total.groupby('date_only',as_index = False) \
                         .size() \
                         .rename(columns={'size':'count_trips'}) \
                         .sort_values('count_trips',ascending=False)
print("\n Метрика 1: Количество поездок по дням")
display(trips_per_day)

#метрика 2: выручка по дням и часам;
revenue_per_days_hour = obt_total.groupby(['date_only','hour_only'],as_index=False) \
                                 .aggregate({'total_amount':'sum'}) \
                                 .rename(columns={'total_amount':'revenue'}) \
                                 .sort_values(['date_only','hour_only'])
revenue_per_days_hour

print("\n Метрика 2: Выручка по дням и часам")
display(revenue_per_days_hour)

#метрика 3: средний чек поездки;
avg_revenue_per_trip = obt_total.groupby('date_only',as_index=False) \
                                .aggregate({'total_amount':'mean'}) \
                                .rename(columns={'total_amount':'avg_per_trip'})
avg_revenue_per_trip

print("\n Метрика 3: Средний чек поездки")
display(avg_revenue_per_trip)

#метрика 4: средняя длительность поездки;
obt_total['trip'] = (obt_total['tpep_dropoff_datetime']-obt_total['tpep_pickup_datetime']).dt.total_seconds()/ 60
avg_duration_per_trip = obt_total.groupby('date_only', as_index=False) \
                        .aggregate({'trip':'mean'}) \
                        .rename(columns={'trip':'trip_min'}) \
                        .sort_values('trip_min',ascending=False)
avg_duration_per_trip

print("\n Метрика 4: Средняя длительность поездки")
display(avg_duration_per_trip)

#метрика 5: среднее расстояние поездки;
avg_trip = obt_total.groupby('date_only', as_index = False) \
                    .aggregate({'trip_distance':'mean'}) \
                    .sort_values('trip_distance',ascending = False)
avg_trip

print("\n Метрика 5: Среднее расстояние поездки")
display(avg_trip)

#метрика 6: популярные зоны посадки и высадки;
popular_zones = obt_total.groupby(['pickup_zone','dropoff_zone'], as_index= False) \
                         .size() \
                         .rename(columns={'size':'count_trip'}) \
                         .sort_values('count_trip', ascending=False)
popular_zones.head(5)

print("\n Метрика 6: Популярные маршруты (Топ-5)")
display(popular_zones.head(5))

#метрика 7: Top зон для посадок
top_pickup_zones = obt_total.groupby('pickup_zone', as_index= False) \
                            .size() \
                            .rename(columns={'size':'count_pickup_zone'}) \
                            .sort_values('count_pickup_zone', ascending= False)
top_pickup_zones.head(5)

print("\n Метрика 7: Топ зон посадки (Топ-5)")
display(top_pickup_zones.head(5))

#метрика 8: Top zone для высадки
top_dropoff_zones = obt_total.groupby('dropoff_zone', as_index= False) \
                             .size() \
                             .rename(columns={'size':'count_dropoff_zone'}) \
                             .sort_values('count_dropoff_zone', ascending= False)
top_dropoff_zones.head(5)

print("\n Метрика 8: Топ зон высадки (Топ-5) ")
display(top_dropoff_zones.head(5))

#метрика 9: распределение поездок по часам суток;
count_trips_per_hour = obt_total.groupby(['date_only','hour_only'],as_index= False) \
                                .size() \
                                .rename(columns={'size':'count_trips_perhour'}) \
                                .sort_values('hour_only', ascending= False)
count_trips_per_hour

print("\n Метрика 9: Распределение по часам (Топ-5)")
display(count_trips_per_hour.head(5))

#метрика 10: аномальные поездки по стоимости, длительности или расстоянию.
obt_total[['total_amount','trip_distance', 'trip']].describe()

print("\n Метрика 10: Статистические характеристики числовых полей ")
display(obt_total[['total_amount', 'trip_distance', 'trip']].describe())

anomalii = obt_total[(obt_total['total_amount']<=0) | (obt_total['trip_distance']==0) | (obt_total['trip']>300)]

clean_obt_total = obt_total[(obt_total['total_amount']>0) & (obt_total['trip_distance']>0) & (obt_total['trip']<300)]

print(f'\n ОТЧЕТ О КАЧЕСТВЕ ДАННЫХ (DATA QUALITY REPORT) ')
print(f'Было строк в выгрузке DWH: {len(obt_total):,}')
print(f'Стало чистых строк для BI: {len(clean_obt_total):,}')
print(f'Выявлено аномалий (ошибки приборов): {len(anomalii):,}')

 Метрика 1: Количество поездок по дням

    date_only  count_trips
3  2019-01-01        64629
4  2019-01-02        34367
2  2018-12-31           30
0  2008-12-31            1
1  2009-01-01            1
5  2019-01-03            1

 Метрика 2: Выручка по дням и часам

     date_only  hour_only    revenue
0   2008-12-31         23      58.56
1   2009-01-01          0       3.30
2   2018-12-31         15      73.14
3   2018-12-31         16     115.23
4   2018-12-31         17     252.62
5   2018-12-31         21      17.30
6   2018-12-31         22      53.16
7   2019-01-01          0      58.56
8   2019-01-01          1      17.76
9   2019-01-01          2      72.11
10  2019-01-01          3     185.29
11  2019-01-01          4     115.22
12  2019-01-01          5     221.22
13  2019-01-01          6      79.85
14  2019-01-01          7     110.72
15  2019-01-01          8     321.57
16  2019-01-01          9    1003.95
17  2019-01-01         10   38939.06
18  2019-01-01         11   75255.81
19  2019-01-01         12   91734.16
20  2019-01-01         13   94693.91
21  2019-01-01         14  107124.05
22  2019-01-01         15  108570.15
23  2019-01-01         16  107616.07
24  2019-01-01         17  117747.24
25  2019-01-01         18  136718.44
26  2019-01-01         19   47829.62
27  2019-01-01         20   40956.22
28  2019-01-01         21   41897.53
29  2019-01-01         22   34670.78
30  2019-01-01         23   26914.36
31  2019-01-02          0   17966.32
32  2019-01-02          1    9303.64
33  2019-01-02          2    4842.82
34  2019-01-02          3    4920.28
35  2019-01-02          4    7752.72
36  2019-01-02          5   18332.84
37  2019-01-02          6   35167.10
38  2019-01-02          7   48513.30
39  2019-01-02          8   58559.85
40  2019-01-02          9   55511.44
41  2019-01-02         10   55706.60
42  2019-01-02         11   57314.22
43  2019-01-02         12   60721.77
44  2019-01-02         13   68094.13
45  2019-01-02         14   21096.22
46  2019-01-03         18      14.30

 Метрика 3: Средний чек поездки

    date_only  avg_per_trip
0  2008-12-31     58.560000
1  2009-01-01      3.300000
2  2018-12-31     17.048333
3  2019-01-01     16.600190
4  2019-01-02     15.241460
5  2019-01-03     14.300000

 Метрика 4: Средняя длительность поездки

    date_only    trip_min
2  2018-12-31  289.061667
0  2008-12-31   44.116667
3  2019-01-01   17.655709
5  2019-01-03   17.600000
4  2019-01-02   12.231006
1  2009-01-01    0.083333

 Метрика 5: Среднее расстояние поездки

    date_only  trip_distance
0  2008-12-31      20.670000
2  2018-12-31       3.747000
3  2019-01-01       3.558446
4  2019-01-02       3.015375
5  2019-01-03       2.990000
1  2009-01-01       0.010000

 Метрика 6: Популярные маршруты (Топ-5)

                pickup_zone           dropoff_zone  count_trip
4714                     NV                     NV        1726
6225  Upper East Side South  Upper East Side North         478
6120  Upper East Side North  Upper East Side South         456
6119  Upper East Side North  Upper East Side North         420
6226  Upper East Side South  Upper East Side South         362

 Метрика 7: Топ зон посадки (Топ-5)

                      pickup_zone  count_pickup_zone
153  Penn Station/Madison Sq West               4934
100                   JFK Airport               4098
109             LaGuardia Airport               4002
194         Upper East Side North               3677
195         Upper East Side South               3654

 Метрика 8: Топ зон высадки (Топ-5)

                  dropoff_zone  count_dropoff_zone
148             Midtown Center                4207
215  Times Sq/Theatre District                3951
221      Upper East Side North                3625
222      Upper East Side South                3326
149               Midtown East                3045

 Метрика 9: Распределение по часам (Топ-5)

     date_only  hour_only  count_trips_perhour
0   2008-12-31         23                    1
30  2019-01-01         23                 1404
6   2018-12-31         22                    1
29  2019-01-01         22                 1899
28  2019-01-01         21                 2388

 Метрика 10: Статистические характеристики числовых полей

       total_amount  trip_distance          trip
count  99029.000000   99029.000000  99029.000000
mean      16.129058       3.370167     15.855431
std       15.611526       4.453264     72.974856
min        0.300000       0.010000      0.000000
25%        7.800000       1.000000      5.666667
50%       10.560000       1.700000      9.433333
75%       16.550000       3.300000     15.616667
max      426.800000      79.090000   1439.766667

 ОТЧЕТ О КАЧЕСТВЕ ДАННЫХ (DATA QUALITY REPORT)
Было строк в выгрузке DWH: 99,029
Стало чистых строк для BI: 98,740
Выявлено аномалий (ошибки приборов): 289